apiVersion: v1
kind: Service
metadata:
  name: simple-app
  namespace: example
  labels:
    app: simple-app
spec:
  selector:
    app: simple-app
  ports:
  - name: http
    port: 80
    targetPort: 8080

